import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { isLocalArtifactPath } from "../build-path-policy.js";

describe("bundle path policy", () => {
  it("does not treat an .omx parent worktree as bundled local state", () => {
    const root = join("/tmp", ".omx", "worktrees", "release", "dsh", "packages", "knowledge", "oh-story");
    expect(isLocalArtifactPath(root, join(root, "manifest.json"))).toBe(false);
    expect(isLocalArtifactPath(root, join(root, "skills", "story", "SKILL.md"))).toBe(false);
  });

  it("still removes local state and generated bytecode inside the asset root", () => {
    const root = join("/checkout", "packages", "knowledge", "oh-story");
    expect(isLocalArtifactPath(root, join(root, ".omx", "state.json"))).toBe(true);
    expect(isLocalArtifactPath(root, join(root, "__pycache__"))).toBe(true);
    expect(isLocalArtifactPath(root, join(root, "skills", "story", "__pycache__", "tool.pyc"))).toBe(true);
    expect(isLocalArtifactPath(root, join(root, ".DS_Store"))).toBe(true);
    expect(isLocalArtifactPath(root, join(root, "skills", "story", ".DS_Store"))).toBe(true);
  });
});
